version: '3.8'

services:
  web:
    build: 
      context: ./kegesystem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./kegesystem:/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]